### ISSUE TITLE
Stronghold position

### ISSUE THREAD

**Issue by Kwaice** [blakewedwards/l5r-lcg-octgn#6]
Great mod ! 

Not really an issue, but is it possible to setup the stronghold and its province above the role or at least separate from the other 4 provinces ?

I know you can do it manually by unanchoring the cards but it would be perfect.

**Comment by blakewedwards** [comment]
I've gotten a couple requests for something like this, I'll see what I can do when I adjust the game element positioning. ATM the vertical positioning is more valuable than horizontal positioning at least on some monitors.
