### ISSUE TITLE
Attachments in the back

### ISSUE THREAD

**Issue by tokeru** [blakewedwards/l5r-lcg-octgn#7]
It would be quite useful to always send cards you play to back by default. For now you have to do it for every attachment, and i dont see a drawback by doin it this way.

**Comment by blakewedwards** [comment]
Hmm, the 'play' action should already send attachments to the back, just confirmed that it works for me. Clicking and dragging the attachment from your hand doesn't currently, but I think I can change that. Is this the behavior you're seeing?

**Comment by blakewedwards** [comment]
0.0.1.4 is out which automatically moves attachments that are dragged to the table to the back. Let me know if there's still an issue you're seeing with attachment placement.

**Comment by tokeru** [comment]
Ah thank you very much, you're right. I do not use the play function for attachments normally, so I havn't noticed it. Nice you did it for dragging too though!
